disabled_rules:
    - multiple_closures_with_trailing_closure
    - trailing_whitespace
    - empty_xctest_method
    - opening_brace
opt_in_rules:
  - implicitly_unwrapped_optional
  - modifier_order
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - deployment_target
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fatal_error_message
  - fallthrough
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try 
  - force_unwrapping 
  - function_default_parameter_at_end
  - generic_type_name
  - identical_operands
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - nesting
  - multiline_arguments
  - number_separator
  - no_fallthrough_only
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - xct_specific_matcher
  - yoda_condition

included:
  - Maskbook

excluded:
    - CoreDataStack/Entity
    - Pods
    - Maskbook/Generated
    - DevelopmentPod
    - Localization

cyclomatic_complexity:
    warning: 12

file_length:
    warning: 500
    error: 550

function_body_length:
    warning: 80

line_length:
    warning: 150
    ignores_comments: true
    
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 3
    error: 6

identifier_name:
    allowed_symbols: "_"
    min_length:  # only min_length
        warning: 1 # only error
    excluded: # excluded via string array
        - id
        - to
        - vc
        - ID

type_name:
    excluded: 
        - ID

# custom_rules:
#     no_underscore_in_identifier:
#       include: ".*\\.swift"
#       name: "No underscore for identifier"
#       regex: "(_)"
#       message: "Should not use underscore for identifier"
#       severity: warning
#       match_kinds: 
#         - identifier
