name: iOS binary build & publish to TestFlight

on:
  push:
    branches: [ release/** ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
          p12-password: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: Install Dependencies
        run: pod install --repo-update

      - name: Restore Secrets
        env: 
          GOOGLE_SERVICE_PLIST: ${{ secrets.GOOGLE_SERVICE_PLIST }}
          SECRECT_SWIFT: ${{ secrets.SECRECT_SWIFT }}
          API_KEY_SWIFT: ${{ secrets.API_KEY_SWIFT }}
        run: |
          echo $GOOGLE_SERVICE_PLIST | base64 --decode > GoogleService-Info.plist
          cd Maskbook/Resources
          echo $SECRECT_SWIFT | base64 --decode > Secrets.swift
          echo $API_KEY_SWIFT | base64 --decode > APIKey.swift

      - name: Update Localization
        run: ./update_localization.sh
    
      - name: Build & upload iOS binary
        run: bundle exec fastlane build_upload_testflight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
 
      - name: Upload app-store ipa and dsyms to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-store ipa & dsyms
          path: |
            ${{ github.workspace }}/mask-iOS.ipa
            ${{ github.workspace }}/*.app.dSYM.zip
